# Generated by Django 5.2.8 on 2025-11-29 00:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_membership"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="membership",
            name="Role",
        ),
        migrations.AddField(
            model_name="membership",
            name="role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("agent", "Agent"), ("viewer", "Viewer")],
                default="viewer",
                max_length=20,
            ),
        ),
    ]
