# Generated by Django 5.2.8 on 2025-11-29 00:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_ticket"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ticket",
            old_name="Priority",
            new_name="priority",
        ),
        migrations.RenameField(
            model_name="ticket",
            old_name="Status",
            new_name="status",
        ),
    ]
