# Generated by Django 5.2.8 on 2025-12-08 11:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_jobrun_triggered_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="jobrun",
            name="idempotency_key",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddConstraint(
            model_name="jobrun",
            constraint=models.UniqueConstraint(
                fields=("ticket", "idempotency_key"),
                name="uniq_jobrun_ticket_idempotency_key",
            ),
        ),
    ]
