# Generated by Django 5.2.8 on 2025-12-08 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_alter_jobrun_idempotency_key"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketevent",
            name="job_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="core.jobrun",
            ),
        ),
        migrations.AlterField(
            model_name="suggestion",
            name="job_run",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="suggestion",
                to="core.jobrun",
            ),
        ),
        migrations.AddConstraint(
            model_name="ticketevent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("job_run__isnull", False)),
                fields=("ticket", "event_type", "job_run"),
                name="uniq_ticketevent_ticket_type_jobrun",
            ),
        ),
    ]
