# Generated by Django 5.2.8 on 2025-12-12 14:08

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_document_documentchunk_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentchunk",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=1536, null=True
            ),
        ),
    ]
