# Generated by Django 5.2.8 on 2025-12-12 14:08

from django.contrib.postgres.operations import CreateExtension
from pgvector.django import VectorField
from core.models import EMBED_DIM
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_document_documentchunk_and_more"),
    ]

    operations = [
        # Ensure pgvector extension exists in this DB
        CreateExtension("vector"),
        # Then add the vector column
        migrations.AddField(
            model_name="documentchunk",
            name="embedding",
            field=VectorField(dimensions=EMBED_DIM, null=True, blank=True),
        ),
    ]
