# Generated by Django 5.2.8 on 2025-12-13 23:41

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_documentchunk_embedding"),
    ]

    operations = [
        migrations.AddField(
            model_name="suggestion",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="documentchunk",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=384, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ticketevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("status_changed", "Status Changed"),
                    ("priority_changed", "Priority Changed"),
                    ("assigned_team_changed", "Assigned Team Changed"),
                    ("comment_added", "Comment Added"),
                    ("ai_triage_ran", "AI Triage Ran"),
                    ("ai_suggestion_created", "AI Suggestion Created"),
                    ("auto_resolution_applied", "Auto Resolution Applied"),
                    ("suggestion_approved", "Suggestion approved"),
                    ("suggestion_rejected", "Suggestion rejected"),
                ],
                max_length=50,
            ),
        ),
    ]
