# Generated by Django 5.2.8 on 2025-12-13 23:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_suggestion_status_alter_documentchunk_embedding_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="suggestion",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
