# Generated by Django 5.2.8 on 2025-12-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_alter_suggestion_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobrun",
            name="attempt_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="jobrun",
            name="last_attempt_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="suggestion",
            name="citations",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="suggestion",
            name="classification",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="suggestion",
            name="confidence",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
